export const names = {
    SINGUP:"SINGUP",
    SINGIN:"SINGIN",
    HOME:"HOME",
    START:"START",
    ADMIN:"ADMIN",
    ADD:"ADD",
    MANAGEBUSINESS:"MANAGEBUSINESS",
    ADDCATEGORY:"ADDCATEGORY",
    UPDATEBUSINESS:"UPDATE",
    MANAGE_CATEGORY:"MANAGE_CATEGORY",
    UPDATE_CATEGORY:"UPDATE_CATEGOEY"
}